call xcompilebcc64 animation
call xcompilebcc64 barcode
call xcompilebcc64 browse
call xcompilebcc64 browse2
call xcompilebcc64 button
call xcompilebcc64 buttonex
call xcompilebcc64 checkbox
call xcompilebcc64 checkbox2
call xcompilebcc64 combobox
call xcompilebcc64 datepicker
call xcompilebcc64 dialog
call xcompilebcc64 dialog2
call xcompilebcc64 dialog3
call xcompilebcc64 getcombobox
call xcompilebcc64 getcombobox2
call xcompilebcc64 getcombobox3
call xcompilebcc64 getdatepicker
call xcompilebcc64 getipaddress
call xcompilebcc64 grid
call xcompilebcc64 listbox
call xcompilebcc64 mainwindow
call xcompilebcc64 masks
call xcompilebcc64 mdichild
call xcompilebcc64 menu
call xcompilebcc64 menu2
call xcompilebcc64 monthcalendar
call xcompilebcc64 nicebutton
call xcompilebcc64 radiobutton
call xcompilebcc64 radiobutton2
call xcompilebcc64 static
call xcompilebcc64 status
call xcompilebcc64 tab
call xcompilebcc64 tab2
call xcompilebcc64 tab3
call xcompilebcc64 tab4
call xcompilebcc64 timer
call xcompilebcc64 timer2
call xcompilebcc64 trackbar
