call xcompilemingw64 animation
call xcompilemingw64 barcode
call xcompilemingw64 browse
call xcompilemingw64 browse2
call xcompilemingw64 button
call xcompilemingw64 buttonex
call xcompilemingw64 checkbox
call xcompilemingw64 checkbox2
call xcompilemingw64 combobox
call xcompilemingw64 datepicker
call xcompilemingw64 dialog
call xcompilemingw64 dialog2
call xcompilemingw64 dialog3
call xcompilemingw64 getcombobox
call xcompilemingw64 getcombobox2
call xcompilemingw64 getcombobox3
call xcompilemingw64 getdatepicker
call xcompilemingw64 getipaddress
call xcompilemingw64 grid
call xcompilemingw64 listbox
call xcompilemingw64 mainwindow
call xcompilemingw64 masks
call xcompilemingw64 mdichild
call xcompilemingw64 menu
call xcompilemingw64 menu2
call xcompilemingw64 monthcalendar
call xcompilemingw64 nicebutton
call xcompilemingw64 radiobutton
call xcompilemingw64 radiobutton2
call xcompilemingw64 static
call xcompilemingw64 status
call xcompilemingw64 tab
call xcompilemingw64 tab2
call xcompilemingw64 tab3
call xcompilemingw64 tab4
call xcompilemingw64 timer
call xcompilemingw64 timer2
call xcompilemingw64 trackbar
