call xcompile animation
call xcompile browse
call xcompile browse2
call xcompile button
call xcompile checkbox
call xcompile checkbox2
call xcompile combobox
call xcompile datepicker
call xcompile dialog
call xcompile dialog2
call xcompile dialog3
call xcompile getcombobox
call xcompile getcombobox2
call xcompile getcombobox3
call xcompile getdatepicker
call xcompile grid
call xcompile listbox
call xcompile mainwindow
call xcompile masks
call xcompile mdichild
call xcompile menu
call xcompile menu2
call xcompile monthcalendar
call xcompile nicebutton
call xcompile radiobutton
call xcompile radiobutton2
call xcompile static
call xcompile status
call xcompile tab
call xcompile tab2
call xcompile tab3
call xcompile tab4
call xcompile timer
call xcompile timer2
