call xcompilemingw32 animation
call xcompilemingw32 barcode
call xcompilemingw32 browse
call xcompilemingw32 browse2
call xcompilemingw32 button
call xcompilemingw32 buttonex
call xcompilemingw32 checkbox
call xcompilemingw32 checkbox2
call xcompilemingw32 combobox
call xcompilemingw32 datepicker
call xcompilemingw32 dialog
call xcompilemingw32 dialog2
call xcompilemingw32 dialog3
call xcompilemingw32 getcombobox
call xcompilemingw32 getcombobox2
call xcompilemingw32 getcombobox3
call xcompilemingw32 getdatepicker
call xcompilemingw32 getipaddress
call xcompilemingw32 grid
call xcompilemingw32 listbox
call xcompilemingw32 mainwindow
call xcompilemingw32 masks
call xcompilemingw32 mdichild
call xcompilemingw32 menu
call xcompilemingw32 menu2
call xcompilemingw32 monthcalendar
call xcompilemingw32 nicebutton
call xcompilemingw32 radiobutton
call xcompilemingw32 radiobutton2
call xcompilemingw32 static
call xcompilemingw32 status
call xcompilemingw32 tab
call xcompilemingw32 tab2
call xcompilemingw32 tab3
call xcompilemingw32 tab4
call xcompilemingw32 timer
call xcompilemingw32 timer2
call xcompilemingw32 trackbar
