call xcompilemsvc32 animation
call xcompilemsvc32 barcode
call xcompilemsvc32 browse
call xcompilemsvc32 browse2
call xcompilemsvc32 button
call xcompilemsvc32 buttonex
call xcompilemsvc32 checkbox
call xcompilemsvc32 checkbox2
call xcompilemsvc32 combobox
call xcompilemsvc32 datepicker
call xcompilemsvc32 dialog
call xcompilemsvc32 dialog2
call xcompilemsvc32 dialog3
call xcompilemsvc32 getcombobox
call xcompilemsvc32 getcombobox2
call xcompilemsvc32 getcombobox3
call xcompilemsvc32 getdatepicker
call xcompilemsvc32 getipaddress
call xcompilemsvc32 grid
call xcompilemsvc32 listbox
call xcompilemsvc32 mainwindow
call xcompilemsvc32 masks
call xcompilemsvc32 mdichild
call xcompilemsvc32 menu
call xcompilemsvc32 menu2
call xcompilemsvc32 monthcalendar
call xcompilemsvc32 nicebutton
call xcompilemsvc32 radiobutton
call xcompilemsvc32 radiobutton2
call xcompilemsvc32 static
call xcompilemsvc32 status
call xcompilemsvc32 tab
call xcompilemsvc32 tab2
call xcompilemsvc32 tab3
call xcompilemsvc32 tab4
call xcompilemsvc32 timer
call xcompilemsvc32 timer2
call xcompilemsvc32 trackbar
