call xcompilemsvc64 animation
call xcompilemsvc64 barcode
call xcompilemsvc64 browse
call xcompilemsvc64 browse2
call xcompilemsvc64 button
call xcompilemsvc64 buttonex
call xcompilemsvc64 checkbox
call xcompilemsvc64 checkbox2
call xcompilemsvc64 combobox
call xcompilemsvc64 datepicker
call xcompilemsvc64 dialog
call xcompilemsvc64 dialog2
call xcompilemsvc64 dialog3
call xcompilemsvc64 getcombobox
call xcompilemsvc64 getcombobox2
call xcompilemsvc64 getcombobox3
call xcompilemsvc64 getdatepicker
call xcompilemsvc64 getipaddress
call xcompilemsvc64 grid
call xcompilemsvc64 listbox
call xcompilemsvc64 mainwindow
call xcompilemsvc64 masks
call xcompilemsvc64 mdichild
call xcompilemsvc64 menu
call xcompilemsvc64 menu2
call xcompilemsvc64 monthcalendar
call xcompilemsvc64 nicebutton
call xcompilemsvc64 radiobutton
call xcompilemsvc64 radiobutton2
call xcompilemsvc64 static
call xcompilemsvc64 status
call xcompilemsvc64 tab
call xcompilemsvc64 tab2
call xcompilemsvc64 tab3
call xcompilemsvc64 tab4
call xcompilemsvc64 timer
call xcompilemsvc64 timer2
call xcompilemsvc64 trackbar
