call xcompile64 animation
call xcompile64 browse
call xcompile64 browse2
call xcompile64 button
call xcompile64 checkbox
call xcompile64 checkbox2
call xcompile64 combobox
call xcompile64 datepicker
call xcompile64 dialog
call xcompile64 dialog2
call xcompile64 dialog3
call xcompile64 getcombobox
call xcompile64 getcombobox2
call xcompile64 getcombobox3
call xcompile64 getdatepicker
call xcompile64 grid
call xcompile64 listbox
call xcompile64 mainwindow
call xcompile64 mdichild
call xcompile64 menu
call xcompile64 menu2
call xcompile64 monthcalendar
call xcompile64 nicebutton
call xcompile64 radiobutton
call xcompile64 radiobutton2
call xcompile64 static
call xcompile64 tab
call xcompile64 tab2
call xcompile64 tab3
call xcompile64 tab4
call xcompile64 timer
call xcompile64 timer2
