call xcompileclang32 animation
call xcompileclang32 barcode
call xcompileclang32 browse
call xcompileclang32 browse2
call xcompileclang32 button
call xcompileclang32 buttonex
call xcompileclang32 checkbox
call xcompileclang32 checkbox2
call xcompileclang32 combobox
call xcompileclang32 datepicker
call xcompileclang32 dialog
call xcompileclang32 dialog2
call xcompileclang32 dialog3
call xcompileclang32 getcombobox
call xcompileclang32 getcombobox2
call xcompileclang32 getcombobox3
call xcompileclang32 getdatepicker
call xcompileclang32 getipaddress
call xcompileclang32 grid
call xcompileclang32 listbox
call xcompileclang32 mainwindow
call xcompileclang32 masks
call xcompileclang32 mdichild
call xcompileclang32 menu
call xcompileclang32 menu2
call xcompileclang32 monthcalendar
call xcompileclang32 nicebutton
call xcompileclang32 radiobutton
call xcompileclang32 radiobutton2
call xcompileclang32 static
call xcompileclang32 status
call xcompileclang32 tab
call xcompileclang32 tab2
call xcompileclang32 tab3
call xcompileclang32 tab4
call xcompileclang32 timer
call xcompileclang32 timer2
call xcompileclang32 trackbar
