call xcompilebcc32 animation
call xcompilebcc32 barcode
call xcompilebcc32 browse
call xcompilebcc32 browse2
call xcompilebcc32 button
call xcompilebcc32 buttonex
call xcompilebcc32 checkbox
call xcompilebcc32 checkbox2
call xcompilebcc32 combobox
call xcompilebcc32 datepicker
call xcompilebcc32 dialog
call xcompilebcc32 dialog2
call xcompilebcc32 dialog3
call xcompilebcc32 getcombobox
call xcompilebcc32 getcombobox2
call xcompilebcc32 getcombobox3
call xcompilebcc32 getdatepicker
call xcompilebcc32 getipaddress
call xcompilebcc32 grid
call xcompilebcc32 listbox
call xcompilebcc32 mainwindow
call xcompilebcc32 masks
call xcompilebcc32 mdichild
call xcompilebcc32 menu
call xcompilebcc32 menu2
call xcompilebcc32 monthcalendar
call xcompilebcc32 nicebutton
call xcompilebcc32 radiobutton
call xcompilebcc32 radiobutton2
call xcompilebcc32 static
call xcompilebcc32 status
call xcompilebcc32 tab
call xcompilebcc32 tab2
call xcompilebcc32 tab3
call xcompilebcc32 tab4
call xcompilebcc32 timer
call xcompilebcc32 timer2
call xcompilebcc32 trackbar
