call xcompileclang64 animation
call xcompileclang64 barcode
call xcompileclang64 browse
call xcompileclang64 browse2
call xcompileclang64 button
call xcompileclang64 buttonex
call xcompileclang64 checkbox
call xcompileclang64 checkbox2
call xcompileclang64 combobox
call xcompileclang64 datepicker
call xcompileclang64 dialog
call xcompileclang64 dialog2
call xcompileclang64 dialog3
call xcompileclang64 getcombobox
call xcompileclang64 getcombobox2
call xcompileclang64 getcombobox3
call xcompileclang64 getdatepicker
call xcompileclang64 getipaddress
call xcompileclang64 grid
call xcompileclang64 listbox
call xcompileclang64 mainwindow
call xcompileclang64 masks
call xcompileclang64 mdichild
call xcompileclang64 menu
call xcompileclang64 menu2
call xcompileclang64 monthcalendar
call xcompileclang64 nicebutton
call xcompileclang64 radiobutton
call xcompileclang64 radiobutton2
call xcompileclang64 static
call xcompileclang64 status
call xcompileclang64 tab
call xcompileclang64 tab2
call xcompileclang64 tab3
call xcompileclang64 tab4
call xcompileclang64 timer
call xcompileclang64 timer2
call xcompileclang64 trackbar
