HB_INC_COMPILE=$(TOP)../include -I$(TOP)$(ROOT)include
ROOT=../../../
C_SOURCES=\
	commond.c \
	control.c \
	edit.c \
	cxshade.c \
	dialog.c \
	draw.c \
	drawtext.c \
	freeimg.c \
	menu_c.c \
	message.c \
	misc.c \
	pager.c \
	registry.c \
	shellapi.c \
	media_c.c \
	richedit.c \
	resource.c \
	wprint.c \
	window.c \
	nice.c \
	grid.c \
	c_ipaddr.c
	
PRG_SOURCES=\
	hfont.prg \
	hpen.prg \
	hbrush.prg \
	hbitmap.prg \
	hicon.prg \
	errorsys.prg \
	guimain.prg \
	hbrowse.prg \
	hcheck.prg \
	hcombo.prg \
	hcontrol.prg \
	hstatus.prg \
	hstatic.prg \
	hbutton.prg \
	hbuttonex.prg \
	hgroup.prg \
	hline.prg \
	hcwindow.prg \
	hobject.prg \
	hdatepic.prg \
	hedit.prg \
	hfreeimg.prg \
	hfrmtmpl.prg \
	hgraph.prg \
	hownbtn.prg \
	hpanel.prg \
	hprinter.prg \
	hradio.prg \
	hriched.prg \
	htab.prg \
	hupdown.prg \
	hwindow.prg \
	hwinprn.prg \
	menu.prg \
	repexec.prg \
	hprogres.prg \
	hdialog.prg \
	htimer.prg \
	htree.prg \
	hsplit.prg \
	hsayimg.prg \
	hshbtn.prg \
	richtext.prg \
	hnice.prg \
	hgrid.prg \
	hrect.prg \
	hpager.prg \
	hrebar.c \
	htrackbr.prg \
	hmonthc.prg \
	hipedit.prg	\
	hhyper.prg \
	hdc.prg
	
LIBNAME=hwgui

DIRS=\
	procmisc \
	qhtm


include $(TOP)$(ROOT)config/lib.cf
include $(TOP)$(ROOT)config/dir.cf
